"""Scaffold generator for Mode-2 project.yaml configs (`maestro init`).

Generates a commented YAML template with values autofilled from the git
environment. The generated content is self-checked against the pydantic
schema before being returned, so `maestro init` can never emit a config
the loader rejects (this also catches template drift when the schema
evolves).
"""

import subprocess
from pathlib import Path
from string import Template

import yaml
from pydantic import ValidationError

from maestro.models import OrchestratorConfig


class ScaffoldError(Exception):
    """Raised when the generated config fails its schema self-check."""


REPO_URL_PLACEHOLDER = "https://github.com/OWNER/REPO"

_TEMPLATE = Template("""\
# Maestro Multi-Process Orchestrator configuration.
# Generated by `maestro init`. Full reference: examples/project.yaml
# in the Maestro repository.
#
# Usage:
#   maestro validate project.yaml
#   maestro orchestrate project.yaml

# --- Project metadata ---

project: $project

# Natural-language description of the project.
# If the `workstreams` section is removed, Maestro uses this description
# to auto-decompose the project via Claude CLI.
description: |
  TODO: describe what should be built.

# --- Repository settings ---

# GitHub remote URL (used for PR creation via gh CLI)
repo_url: $repo_url$repo_url_comment

# Local path to the repository (absolute or ~)
repo_path: $repo_path

# Base directory where git worktrees are created
workspace_base: $workspace_base

# --- Execution settings ---

max_concurrent: 3
base_branch: $base_branch
branch_prefix: "feature/"
auto_pr: true

# --- Workstreams ---
# Each workstream runs in an isolated git worktree on its own branch.
# `scope` globs declare file ownership; keep scopes non-overlapping so
# parallel workstreams cannot conflict. `depends_on` orders execution.

workstreams:
  - id: example-workstream
    title: "Example workstream"
    description: |
      TODO: describe this work unit.
    scope:
      - "src/example/**"
    depends_on: []
    priority: 0

# --- Notifications (optional) ---
# notifications:
#   desktop: true
""")


def _git_query(args: list[str], cwd: Path) -> str | None:
    """Run a read-only git query; None when git/repo/value is unavailable.

    Private to scaffold: the rest of Maestro talks to git through the
    async, worktree-oriented GitManager. Do not import this elsewhere;
    if a third sync-git caller appears, promote it deliberately.
    """
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _detect_base_branch(cwd: Path) -> str:
    """origin default branch -> current branch -> 'main'."""
    ref = _git_query(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], cwd)
    if ref and "/" in ref:
        return ref.split("/", 1)[1]
    return _git_query(["branch", "--show-current"], cwd) or "main"


def generate_project_yaml(cwd: Path, project: str | None = None) -> str:
    """Generate project.yaml content for the given directory.

    Args:
        cwd: Directory the config describes (usually the repo root).
        project: Project name override; defaults to the directory name.

    Returns:
        YAML text that is guaranteed to pass OrchestratorConfig.

    Raises:
        ScaffoldError: If the generated content fails the schema
            self-check (template drift bug — never expected at runtime).
    """
    name = project or cwd.name
    repo_url = _git_query(["remote", "get-url", "origin"], cwd)

    content = _TEMPLATE.substitute(
        project=name,
        repo_url=repo_url or REPO_URL_PLACEHOLDER,
        repo_url_comment=(
            "" if repo_url else "  # TODO: no origin remote found — fill in"
        ),
        repo_path=str(cwd.resolve()),
        workspace_base=f"/tmp/maestro-ws/{name}",
        base_branch=_detect_base_branch(cwd),
    )

    try:
        OrchestratorConfig(**yaml.safe_load(content))
    except (yaml.YAMLError, ValidationError) as exc:
        msg = (
            "internal error: generated config does not satisfy the "
            f"OrchestratorConfig schema: {exc}"
        )
        raise ScaffoldError(msg) from exc

    return content
